# @HostAddress = https://qbank.yuxiaoyu.top/api
@HostAddress = https://localhost:7224/api
@email = admin@qq.com
@badPassword = password
@password = Az.123123!

# 注册用户
POST {{HostAddress}}/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "confirmPassword": "{{password}}"
}

###

# 使用密码登录获取Token
POST {{HostAddress}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

# Tokken
@accessToken = CfDJ8AfsKNinfjRPgNkrR0o_RlBgYV82C8RDLLw3KbY6oBMxnGVY3sgT3YQ95zqyp3soTS5rS1jeyflKO3EvQWQ3D_Ak12YjZa2U4CX-WoS00Gxdiv-CJgLJ-N2MyGSq9zccr0-M9T7nyhj8eGRXt3kd4Nrdc8f46Bt2e8ry6e_4BNDmJOm8pVlGUCUGhTCwZBxXp4UHe_V3O1Smivp1P2UMUHdLbto0_ce7cv6Ne2Ve1Xd6bzO0gwEGUIoF_48bUxy1PZWuwbJPyBSo4CtKyHPmmkI7wQBHe1M45xl0kxalGhq_Hoj4PN-pYtJ9GD7caK7OcKabS6mL95uuxcEEHBLHj1wW_FpQASyk23WSi5QgYOlduI1Ot-9QK9sVxKgXDXe9eD1oIgOZKlREWAP3CG6mdlyjV8GfHDCO3RUxfRdBnldmK6hHLehS6pFR1l74nkbyBO_G8sfegxzM_Ej7vWPIeMqZEV2cEYgwWib5P2coSYxsd7fCC1_Db4DvWi2DOFWUN_PDIvy9eZF-VzCRztPKzL3mTo6whFNHVrMN5VXGsYLgCM3pLvfNPlAKaJ3dW2iz1Cberw-4p63KeR6i6hFq4wikg-we7qEOh3EGi5M6Z2D9CMO8eVYxR8IC5N0z8LqYRXgAUNAntY21Jru2oyNzIScRQ-YynM9fWd11Vgntv8N9NBfXaUNzCHFU0vVBjpCqbA
@refreshToken = CfDJ8AfsKNinfjRPgNkrR0o_RlDZZG7V1Tk8whIBFNeDVaPkRSdEw9gBbqwuzawfW-Qff1LUxM-DMBq3XBLU2a3hUxjkbZekxzBhg3gEBm6qcNYTJ2C31a84-m0SjpF65p4NQZoOfqvonwJcIZJx1d_eyUmUWzDczrCS2NuBRoIpJi5-yX7Ok0ioQAGhQkXQoi8WvMGL6avfG6VueX_Ey2Q7DioMnxgQ_tndqALRMfZWPkFCExmTE4sPHJh2wJ-4riPVrIADM3pWFnjHpMRU4xbeyQdKoO6eRZ7xbFg0AjnccvYziZhY3tWjYL9fN8MCw4DNZQrChnyhLMDUv2t7sGqUNdIPeMJcq5k-1WdoRzAkCTJ2BxxU8t3TDian9nPYw9Bh6rZlhcPn4S92Ailv0R5kctjfirHAkbuR2unj8U1lztYV7QJUYi8fbzc-OtvBcYdku1Rbm2_KUwzESILEopJ6zxxIeteVCBFYafLmxWx6JM8UHDoks8uzoJHeajbtfFapEHf7oCOvdlQg4Vl_O7Whx8ctpJU3hacgKXAGSeD5TpDKClUvbzXnziPxC0BeGKxuQT8SwXfZom9lRFJNRI6b5zbXLyAHbuElhyWF5AUxtqhyvz8emgJddGMD2ckCo-puHE_o7-h56fz6NescWMSYjtCO1mlB9OCgul32vyIiXqHoOqQNMfICmTgQh0d5hPTTVg

###

# 刷新Token
POST {{HostAddress}}/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### 用户接口

# 获取用户总数
GET {{HostAddress}}/users/count HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###

# 获取用户列表
GET {{HostAddress}}/users/ HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###

# 根据ID获取用户
GET {{HostAddress}}/users/b23f7e0a-3a76-4f0a-b51f-da03680eaa9d/ HTTP/1.1
Authorization: Bearer {{accessToken}}
Accept: application/json

###

# 修改用户
PUT {{HostAddress}}/users/b23f7e0a-3a76-4f0a-b51f-da03680eaa9d/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "Email": "admin12000@qq.com",
  "userName": "admin0000012",
  "Roles": ["admin","student"]
}

###

# 获取题目总数(一般用于分页)
GET {{HostAddress}}/Questions/count
Authorization: Bearer {{accessToken}}
Accept: application/json

###

# 获取题目列表
GET {{HostAddress}}/Questions/?offset=0&limit=100
Authorization: Bearer {{accessToken}}
Accept: application/json

###

# 根据题目ID获取题目
GET {{HostAddress}}/Questions/31
Authorization: Bearer {{accessToken}}
Accept: application/json


###

# 创建单选题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "测试题目？",
  "QuestionType": 1,
  "DifficultyLevel": 1,
  "CorrectAnswer": "D",
  "Options": [
    {
      "OptionCode": "A",
      "OptionText": "方法论1",
      "IsCorrect": false
    },
    {
      "OptionCode": "B",
      "OptionText": "方法论2",
      "IsCorrect": false
    },
    {
      "OptionCode": "C",
      "OptionText": "方法论3",
      "IsCorrect": false
    },
    {
      "OptionCode": "D",
      "OptionText": "方法论4",
      "IsCorrect": true
    }
  ]
}

###

# 创建多选题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "多选题，题目？",
  "QuestionType": 2,
  "DifficultyLevel": 1,
  "CorrectAnswer": "A,C,D",
  "Options": [
    {
      "OptionCode": "A",
      "OptionText": "方法论1",
      "IsCorrect": true
    },
    {
      "OptionCode": "B",
      "OptionText": "方法论2",
      "IsCorrect": false
    },
    {
      "OptionCode": "C",
      "OptionText": "方法论3",
      "IsCorrect": true
    },
    {
      "OptionCode": "D",
      "OptionText": "方法论4",
      "IsCorrect": true
    }
  ]
}

###

# 创建判断题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "判断题，题目？",
  "QuestionType": 3,
  "DifficultyLevel": 1,
  "CorrectAnswer": "1"
}

###

# 创建填空题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "填空题？",
  "QuestionType": 4,
  "DifficultyLevel": 1,
  "CorrectAnswer": "喔哦喔哦我啊啊啊"
}

###

# 修改题目
PUT {{HostAddress}}/Questions/22
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "CorrectAnswer": "D"
}

###

# 删除题目
DELETE  {{HostAddress}}/Questions/32
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###


### 试卷相关API

# 查询试卷列表
GET {{HostAddress}}/Exams/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# 根据ID查询试卷
GET {{HostAddress}}/Exams/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# 创建试卷
POST {{HostAddress}}/Exams/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "ExamName": "第一套试卷",
  "DifficultyLevel": 2,
  "ExamQuestions": [
    {
      "Order": 1,
      "QuestionId": 22
    },
    {
      "Order": 2,
      "QuestionId": 23
    },
    {
      "Order": 3,
      "QuestionId": 27
    },
    {
      "Order": 4,
      "QuestionId": 30
    }
  ]
}
