# @HostAddress = https://qbank.yuxiaoyu.top/api
@HostAddress = https://localhost:7224/api
@email = admin@qq.com
@badPassword = password
@password = Az.123123!

# 注册用户
POST {{HostAddress}}/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "confirmPassword": "{{password}}"
}

###

# 使用密码登录获取Token
POST {{HostAddress}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

# Tokken
@accessToken = CfDJ8AfsKNinfjRPgNkrR0o_RlCbt9Osi10AfqJfCEaLxKl-3icET-VL7UxEX0P4yolRgqpG-hNplfSV6_B91IhxUdsCXIou3j3Lk5E6TJ8iiO8-lhxUwjkYemgRMHoTQ5TIdmmQVMmLDeHFLb9XrpKvGAvFENb71W7KplsMf2XFk4jpQWiQr8yBEtlfCN3VNL6zvIZ5qQOQe3rX6aY6L797AC6CXcH8m5N1VahL-Nu2EjYSOt9rgwfl1w6uY29AyVDO3a7Wmm0hMVqN1zVoKaiRH2yebw5WrEMjt4GhSSF0eiYsBizKNC63F5itFuxj17yNe-7OM60JxoE0THEYqo3gkSRLI9JLbewRfauyOrQ2Z7Rl0Sz8w6s5XdbSMQO3uU6SONF_n2xgEDBEFHPYwFKwucDwPQRW9YWZ8mpKzGaq6m0fIIXhbYe22rFtyjUdJkFtqfKDppaVs5wpyAz3QLdpFYMoANVqjmRzdA8RIlGb7gLyQuMX3AWmjOpMasiyoGutwvrcdWi84MhcXoXmcERajYpo0Ax_VMYyJLzUTJWtxOF0M6caYsYIQVapnNMZtPaNoygHE9fe0CZafKdszMM7HH92n-eUrDP4Uhi8akucSPRztLEzZGsAgL_MXLBh0-dlT6aprQUF6FND1mdzLxSPSB1EgLWkFqeciXpG7_wr3L2_7YvakBxk_pMgQU7wDTibDA
@refreshToken = CfDJ8AfsKNinfjRPgNkrR0o_RlDGPJ1xAxrSl5pQYA0IAMg87PVCdO_KDecfvbpYpRDMKHwh6ZsurPpULGNMC1ULjNV5aFFYc9EUL8cYDnBxoGBOAj0DyKPn4KvkUf9eyUpz6h_Wt_9z2ADapQxToSTBIp2-1XVWzRpELgrwh4quDS0bgnQLH6Y5h_sNgA4ntbWKSm_2vk6h5pxL2qaLIyx_bSzsIECRIqbWS_LpqS83MBC2sn3q35A7VQ9BYf3Iav9kd3wLtVTlNDXA0c-BIKm_KP95RvWtMBg1Ed1esbnypMfwWkrQFsAnjlcEdSRHe19tNmM_3O6Vax1PDpxIvZDcwzvfnUMzRAKiU-vlTh_qwUwxasCImYZ05o2JG7RQf-B4x7SqjjzP5NwR-ds9mtkW81DW9ERsqknwbr5Fghlsbf6b4lsb7BmAQBZ3iZUSyrLjTAaAeAiDYkvT0FIeEaGjgpSrfcsKCfvUDjN6UxWA7SrUouvmRoz_p-kqGhMYXs7Y9NeNN8fjGUBNUMWSA71wlqne3Tzb8cGy7o7o3xiXpGu7-hafz7ZuY_7lliunWVVgYiJlhysDNZ-Wb2bvngNXJNob0rZU8uSha9qZLObDiOcWfKu-i_txc9gGGe-9luo5PNhms0vrpfaQRkTyIQVg5R2Oelpl-b-ZpjXyL0e8q-hxPvCzY8LY-LduV9GDxCn5ijyEi4KgsriaFPdJd2WZrkr7RD-WP8L79KVzMW38vmFk

###

# 刷新Token
POST {{HostAddress}}/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

# 获取题目总数(一般用于分页)
GET {{HostAddress}}/Questions/count
Authorization: Bearer {{accessToken}}
Accept: application/json

###

# 获取题目列表
GET {{HostAddress}}/Questions/?offset=0&limit=100
Authorization: Bearer {{accessToken}}
Accept: application/json

###

# 根据题目ID获取题目
GET {{HostAddress}}/Questions/22
Authorization: Bearer {{accessToken}}
Accept: application/json


###

# 创建单选题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "测试题目？",
  "QuestionType": 0,
  "CorrectAnswer": "D",
  "Options": [
    {
      "OptionCode": "A",
      "OptionText": "方法论1",
      "IsCorrect": false
    },
    {
      "OptionCode": "B",
      "OptionText": "方法论2",
      "IsCorrect": false
    },
    {
      "OptionCode": "C",
      "OptionText": "方法论3",
      "IsCorrect": false
    },
    {
      "OptionCode": "D",
      "OptionText": "方法论4",
      "IsCorrect": true
    }
  ]
}

###

# 创建多选题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "多选题，题目？",
  "QuestionType": 1,
  "CorrectAnswer": "A,C,D",
  "Options": [
    {
      "OptionCode": "A",
      "OptionText": "方法论1",
      "IsCorrect": true
    },
    {
      "OptionCode": "B",
      "OptionText": "方法论2",
      "IsCorrect": false
    },
    {
      "OptionCode": "C",
      "OptionText": "方法论3",
      "IsCorrect": true
    },
    {
      "OptionCode": "D",
      "OptionText": "方法论4",
      "IsCorrect": true
    }
  ]
}

###

# 创建判断题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "判断题，题目？",
  "QuestionType": 2,
  "CorrectAnswer": "1"
}

###

# 创建填空题目
POST {{HostAddress}}/Questions/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "填空题？",
  "QuestionType": 3,
  "CorrectAnswer": "喔哦喔哦我啊啊啊"
}

###

# 修改题目
PUT {{HostAddress}}/Questions/22
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "CorrectAnswer": "D"
}

###

# 删除题目
DELETE  {{HostAddress}}/Questions/39
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###