@HostAddress = https://localhost:7224
@email = test@x.z
@badPassword = password
@password = P455w0rd!

# Now a valid one
POST {{HostAddress}}/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "confirmPassword": "{{password}}"
}

###

# And the right one. Be sure to copy and paste the tokens from the response.
# Notice you get when the current token will expire in the response.
POST {{HostAddress}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

# these come from the previous response
@accessToken = CfDJ8AfsKNinfjRPgNkrR0o_RlCLoM2n5LR7aDdx2T9q_SagXUeAyku78kWl8MbiLESD5HQwTiER2NFBHXUw8o9p28uBdyGFm3xQeAiKW0kKA-ZX4L7gTHk7hSgpHfKMOJeV-UPzn8iIIdnzIJ9htMrQDeAQuAtR0weFybBG2tVZgQT6vM1AfWaC9fBAvd3lDJN-kWcI5Yhb-Gf-SiPGU21Z7FH1nWl9K23z_H4GaIXlnQftZ1lPMC-FVFL0g1bD7hv7OAUjiotGqNGTYCxB3r2dI-r3DszglkqU77k2uSctO90c7E6w5Qqki2ZEHdR9uQmVdRS-Puxrp08jauZ_xpWjxg5OONfWwsoeXLV13hC_ynT6nmR890mygNrm6XeOBKPM2_iQ6oNk_uZs4gXMhdi4GMWNJyLVApchVu6BhCR3i2r3anbfnd4NjPjSqC6SC3_CQxrFrk0HWo5-o0cMAhlkc5dO9YWcpU4En7iu6oTG9fmTcJZGEi5QkqnFnDRd40jaXj64fI2McWUsnOoYFw2ihDtBzqXXMD0b18GC-IbICVtTZU5ZukqU8LDtzqrS5_2VwFSVpj53jyyBXkW3SpyaBil-CjFuamEuKpAqlxsNCgAnRkGSpy8CjuJf2t99W-Iw8RJgpxN_i2hELCklUkySwgWpsh9f7mlOUgitYO1OG0GKNwp18Erna5MLYztSVo1DxVdfJPV1WgAWIw4oB0bdsUY
@refreshToken = CfDJ8AfsKNinfjRPgNkrR0o_RlDPbgxC875A-1YV49A9zx-bh5dqwaf5NqCHd0AYSmYk1i1ykC9CgfuWsbBtQfA_Y5FT61AG7Vt5DOg9UMe46Kih27H4fr7QwaJwdn6PMxlL0sV0hZr2Ac4kjPZC9UeeDvWff2DRE5JoGA_etsEVuN3jDPH-VLqIUP6aI_oB9hIF_axUdVKldJzM3ZYvhh-rC_9iF1wa4RQPTkmulIDkGd3NIKQrqi4nTWgrLYU8e2RYuCBnQ1XnEZmDE1Pb3hQZLQaj9QtmnOn_17spX2VfhGOEG22TMmsRZKXdKsvx8OcOaTah67cIu7wiv3p3l4-yNReeYSvb-Z682iJmwWMNgA07aDms4LhCkBpxhvg9Ntwqq1PZ6Vl6U8C8Ni71EE20QZgEMsKbuXAaYxfo9U6gpoWHrCnAQReB_5FQlpG8jq8sLGdJzO-zj_AcGuL4Skw90Twh47gZbRqmeyKSVfgmUMmW7N4RHqpvfja2uyRw46Y12dHpJpC5BGytZUBwk3FmI2tcA8Q4L4EBLLgcitFpkdRIeUEmbOuqjZS6oln3chQcOHP6T5q-uqJarMnXw5u_GEU6QIbAZRurt8FUHEo8cFvRPUUH3BjbTPTWcGulvYX_fI1ZhLaNCOLj69XK8P25AmpU6ulPyh6TtUxKdBVxkCjuCrY0RfR-GQU5LrCrfHKbhuzn3xGnHrDfxoqldxBw_3g

###

# Now assume the session is about to expire and you want to extend the session without forcing the user to login again.
POST {{HostAddress}}/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}" 
}

###

GET {{HostAddress}}/Question/?offset=10&limit=10
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{HostAddress}}/Question/1
Authorization: Bearer {{accessToken}}
Accept: application/json


###

POST {{HostAddress}}/Question/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "测试题目？",
  "QuestionType": 1
}

###

PUT {{HostAddress}}/Question/11
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "QuestionText": "测试题目？xxxxaaaax22222x",
  "QuestionType": 3
}

###